# Generated by Django 4.2.11 on 2024-06-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_vote_value_priceshown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
